[TOC]



```{r}
# 软件检测和安装
# Load required libraries
# 加载所需的库
# 加载必要的包
library(ImageGP)
library(pheatmap)
library(RColorBrewer)
library(grid)
library(vegan)
library(dplyr)
library(stringr)


```



## 数据加载

```{r}
# 读取 metadata 和 co-occurrence 数据
data <- "C:/16S/result/ggclusternet/result_1000_igraph2_2_1000/co-occurrence_Grobel_net3.txt"
display_numbers <- "NULL"
outputprefix <- "C:/16S/result/ggclusternet/pheatmap_new"
outputpictype <- "pdf"
renameDuplicateRowNames <- TRUE
logv <- "log10"
log_add <- 0
scale <- "row"
top_n <- 1
statistical_value_type <- "mad"
annotation_row <- "NULL"
annotation_col <- "NULL"   #"C:/16S/result/ggclusternet/metadata_GroupE.txt"  "NULL"
cluster_rows <- TRUE
cluster_cols <- TRUE
clustering_method <- "complete"
clustering_distance_rows <- "pearson"
clustering_distance_cols <- "pearson"
breaks <- "NA"
breaks_mid <- NULL
breaks_digits <- 2
correlation_plot <- "None"
maximum <- Inf
minimum <- -Inf
xtics_angle <- 0
manual_color_vector <- "RdYlBu"
fontsize <- 25
manual_annotation_colors_sidebar <- "NULL"
cutree_cols <- 2
cutree_rows <- 2
kclu <- NA
ytics <- TRUE
xtics <- TRUE
title <- ""
anno_cutree_rows <- TRUE
anno_cutree_cols <- TRUE
label_row_cluster_boundary <- FALSE
label_col_cluster_boundary <- FALSE
label_every_n_rowitems <- 1
label_every_n_colitems <- 1
width <- 20
height <- 15
debug <- FALSE
cluster_cols_variable <- "NULL"
cluster_rows_variable <- "NULL"
remove_cluster_cols_variable_in_annocol <- FALSE
remove_cluster_rows_variable_in_annorow <- FALSE
saveppt <- FALSE


```  



## 调整分列

```{r}
if(breaks == 'NA'){
  breaks <- NA
} else if(breaks != "quantile"){
  breaks <- as.numeric(sp_string2vector(breaks))
}

# 管理颜色向量
manual_color_vector <- sp_string2vector(manual_color_vector)



```    


## 热图绘制

```{r}

if (outputprefix == ""){
  outputprefix <- data
}
filename <- paste0(outputprefix,  '.pheatmap.', outputpictype)

cat(sp_current_time(), "Starting...\n")


sp_pheatmap(
  data = data,
  filename = filename,
  renameDuplicateRowNames = renameDuplicateRowNames,
  logv = logv,
  top_n = top_n,
  statistical_value_type = statistical_value_type,
  log_add = log_add,
  scale = scale,
  annotation_row = annotation_row,
  annotation_col = annotation_col,
  cluster_rows = cluster_rows,
  cluster_cols = cluster_cols,
  clustering_method = clustering_method,
  clustering_distance_rows = clustering_distance_rows,
  clustering_distance_cols = clustering_distance_cols,
  breaks = breaks,
  breaks_mid = breaks_mid,
  breaks_digits = breaks_digits,
  correlation_plot = correlation_plot,
  maximum = maximum,
  minimum = minimum,
  xtics_angle = xtics_angle,
  manual_color_vector = manual_color_vector,
  fontsize = fontsize,
  manual_annotation_colors_sidebar = manual_annotation_colors_sidebar,
  cutree_cols = cutree_cols,
  cutree_rows = cutree_rows,
  anno_cutree_rows = anno_cutree_rows,
  anno_cutree_cols = anno_cutree_cols,
  label_row_cluster_boundary = label_row_cluster_boundary,
  label_col_cluster_boundary = label_col_cluster_boundary,
  label_every_n_rowitems = label_every_n_rowitems,
  label_every_n_colitems = label_every_n_colitems,
  kclu = kclu,
  ytics = ytics,
  xtics = xtics,
  width = width,
  height = height,
  title = title,
  cluster_cols_variable=cluster_cols_variable,
  cluster_rows_variable=cluster_rows_variable,
  remove_cluster_cols_variable_in_annocol=remove_cluster_cols_variable_in_annocol,
  remove_cluster_rows_variable_in_annorow=remove_cluster_rows_variable_in_annorow,
  debug = debug,
  display_numbers = display_numbers,
  saveppt = saveppt
)
cat(sp_current_time(), "Success.\n")





```    

























 

 
 
 