[TOC]



## OTGG苦参碱处理
```{r}
# 软件检测和安装
library(ggplot2)
library(dplyr)
library(tidyr)
library(broom)
library(purrr)
library(ggpubr) # 用于ANOVA结果可视化

# 文件夹位置
file1 = "C:/Matrine_bodydata/"
# 具体文件前标
part = "part_II_"
name = "Matrine_OTGG"
# 文件后标
filemethod1 = "_line_plot"
filemethod2 = "_kruskal"
filemethod3 = "_t_test"
filemethod4 = "_ANOVA"
# 文件种类
filetype1 = ".txt"
filetype2 = ".pdf"
# 生成文件名
datafile <- paste(file1,part,name,filetype1,sep ="")
lineplot <- paste(file1,part,name,filemethod1,filetype2,sep ="")
ttest <- paste(file1,part,name,filemethod3,filetype1,sep ="")
ANOVAt1 <- paste(file1,part,name,filemethod4,filetype1,sep ="")
ANOVAt2 <- paste(file1,part,name,filemethod4,filetype2,sep ="")
kruskal <- paste(file1,part,name,filemethod2,filetype1,sep ="")

print(datafile)
print(lineplot)
print(ttest)
print(ANOVAt1)
print(ANOVAt2)
print(kruskal)

# 读取数据文件
data <- read.table(datafile, header = TRUE, sep = "\t")
# 检查数据框架结构
str(data)
# 转换数据框为长格式，并根据列名称分组
data_long <- data %>%
  pivot_longer(-Time.min, names_to = "Replicate", values_to = "Value") %>%
  mutate(Group = case_when(
    grepl("NC", Replicate) ~ "NC",
    grepl("MD", Replicate) ~ "MD",
    grepl("LMAT", Replicate) ~ "LMAT",
    grepl("HMAT", Replicate) ~ "HMAT"
  ))
# 计算平均值和标准误差
data_summary <- data_long %>%
  group_by(Time.min, Group) %>%
  summarise(
    Mean = mean(Value),
    SE = sd(Value) / sqrt(n())
  )

# 绘制折线图并保存为 PDF 文件
# 高级配色方案 
#colors <- c("NC" = "#440154FF", "MD" = "#31688EFF", "LMAT" = "#35B779FF", "HMAT" = "#FDE725FF")
#colors <- c("NC" = "#FBB4AE", "MD" = "#B3CDE3", "LMAT" = "#CCEBC5", "HMAT" = "#DECBE4")
#colors <- c("NC" = "#1b9e77", "MD" = "#d95f02", "LMAT" = "#7570b3", "HMAT" = "#e7298a" )
#colors <- c("NC" = "#7FC97F", "MD" = "#BEAED4", "LMAT" = "#FDC086", "HMAT" = "#FFFF99")
colors <- c("NC" = "#D7191C", "MD" = "#FDAE61", "LMAT" = "#ABDDA4", "HMAT" = "#2B83BA")
#colors <- c("NC" = "#A6CEE3", "MD" = "#1F78B4", "LMAT" = "#B2DF8A", "HMAT" = "#33A02C")
shapes <- c("NC" = 8, "MD" = 9, "LMAT" = 10, "HMAT" = 11)

# 绘制折线图并保存为 PDF 文件
line_plot <- ggplot(data_summary, aes(x = Time.min, y = Mean, color = Group, shape = Group)) +
  geom_line(size = 0.25) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE), width = 5) +
  labs(x = "Time (min)", y = "Mean Value ± SE", title = "OTGG Test Data with Error Bars") +
  scale_color_manual(values = colors) +
  scale_shape_manual(values = shapes) +
  theme_minimal(base_size = 6) +
  theme(
    plot.title = element_text(size = 6, face = "bold"),
    axis.title = element_text(size = 6),
    axis.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 6),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black")
  )
       
ggsave(lineplot, plot = line_plot, width = 3, height = 2)
line_plot


## 进行T-test
# 分组
control <- data_long %>% filter(Group == "NC")
MD <- data_long %>% filter(Group == "MD")
LMAT <- data_long %>% filter(Group == "LMAT")
HMAT <- data_long %>% filter(Group == "HMAT")


# 进行T检验
t_test_results <- list(
  Control_vs_MD = t.test(control$Value, MD$Value),
  Control_vs_LMAT = t.test(control$Value, LMAT$Value),
  Control_vs_HMAT = t.test(control$Value, HMAT$Value),
  MD_vs_LMAT = t.test(MD$Value, LMAT$Value),
  MD_vs_HMAT = t.test(MD$Value, HMAT$Value),
  LMAT_vs_HMAT = t.test(LMAT$Value, HMAT$Value)
)

# 使用 broom 包中的 tidy 函数将结果转换为数据框，并添加 comparison 列
t_test_results_df <- t_test_results %>%
  map_df(tidy, .id = "comparison")
# 保存T检验结果为txt文件            
write.table(t_test_results_df, file = ttest, sep = "\t", row.names = FALSE, quote = FALSE)
t_test_results_df


## 单因素方差分析(ANOVA)
anova_results <- aov(Value ~ Group, data = data_long)
# 展示ANOVA结果
summary(anova_results)
anova_summary <- summary(anova_results)
# 保存ANOVA结果为txt文件                 
capture.output(anova_summary, file = ANOVAt1)
# 可视化ANOVA结果并保存为PDF文件
anova_plot <- ggboxplot(data_long, x = "Group", y = "Value", 
                        color = "Group", palette = colors, 
                        add = "jitter") + 
  #geom_boxplot(outlier.size = 0, size = 0.75, aes(color = Group)) +  # 调整箱线图的描边宽度
  stat_compare_means(method = "anova", label = "p.signif") +
  theme_minimal(base_size = 6) +
  theme(
    plot.title = element_text(size = 6, face = "bold"),
    axis.title = element_text(size = 6),
    axis.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 6),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black")
  )
# 文件保存
ggsave(ANOVAt2, plot = anova_plot, width = 3, height = 3)
anova_plot


## 克鲁斯卡尔-沃利斯检验kruskal
kruskal_results <- kruskal.test(Value ~ Group, data = data_long)
# 展示克鲁斯卡尔-沃利斯检验结果
kruskal_results                           
capture.output(kruskal_results, file = kruskal)

```    

 


## 8周体重变化
```{r}
# 软件检测和安装
library(ggplot2)
library(dplyr)
library(tidyr)
library(broom)
library(purrr)
library(ggpubr) # 用于ANOVA结果可视化

# 文件夹位置
file1 = "C:/Matrine_bodydata/"
# 具体文件前标
part = "part_II_"
name = "Matrine_8weeks_bodyweight"
# 文件后标
filemethod1 = "_line_plot"
filemethod2 = "_kruskal"
filemethod3 = "_t_test"
filemethod4 = "_ANOVA"
# 文件种类
filetype1 = ".txt"
filetype2 = ".pdf"
# 生成文件名
datafile <- paste(file1,part,name,filetype1,sep ="")
lineplot <- paste(file1,part,name,filemethod1,filetype2,sep ="")
ttest <- paste(file1,part,name,filemethod3,filetype1,sep ="")
ANOVAt1 <- paste(file1,part,name,filemethod4,filetype1,sep ="")
ANOVAt2 <- paste(file1,part,name,filemethod4,filetype2,sep ="")
kruskal <- paste(file1,part,name,filemethod2,filetype1,sep ="")

print(datafile)
print(lineplot)
print(ttest)
print(ANOVAt1)
print(ANOVAt2)
print(kruskal)

# 读取数据文件
data <- read.table(datafile, header = TRUE, sep = "\t")
# 检查数据框架结构
str(data)
# 转换数据框为长格式，并根据列名称分组
data_long <- data %>%
  pivot_longer(-Weeks, names_to = "Replicate", values_to = "Value") %>%
  mutate(Group = case_when(
    grepl("NC", Replicate) ~ "NC",
    grepl("MD", Replicate) ~ "MD",
    grepl("LMAT", Replicate) ~ "LMAT",
    grepl("HMAT", Replicate) ~ "HMAT"
  ))
# 计算平均值和标准误差
data_summary <- data_long %>%
  group_by(Weeks, Group) %>%
  summarise(
    Mean = mean(Value),
    SE = sd(Value) / sqrt(n())
  )

# 绘制折线图并保存为 PDF 文件
# 高级配色方案 
#colors <- c("NC" = "#440154FF", "MD" = "#31688EFF", "LMAT" = "#35B779FF", "HMAT" = "#FDE725FF")
#colors <- c("NC" = "#FBB4AE", "MD" = "#B3CDE3", "LMAT" = "#CCEBC5", "HMAT" = "#DECBE4")
#colors <- c("NC" = "#1b9e77", "MD" = "#d95f02", "LMAT" = "#7570b3", "HMAT" = "#e7298a" )
#colors <- c("NC" = "#7FC97F", "MD" = "#BEAED4", "LMAT" = "#FDC086", "HMAT" = "#FFFF99")
colors <- c("NC" = "#D7191C", "MD" = "#FDAE61", "LMAT" = "#ABDDA4", "HMAT" = "#2B83BA")
#colors <- c("NC" = "#A6CEE3", "MD" = "#1F78B4", "LMAT" = "#B2DF8A", "HMAT" = "#33A02C")
shapes <- c("NC" = 8, "MD" = 9, "LMAT" = 10, "HMAT" = 11)

# 绘制折线图并保存为 PDF 文件
line_plot <- ggplot(data_summary, aes(x = Weeks, y = Mean, color = Group, shape = Group)) +
  geom_line(size = 0.25) +
  geom_point(size = 0.75) +
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.25) +
  labs(x = "Weeks", y = "Mean Value ± SE", title = "OTGG Test Data with Error Bars") +
  scale_color_manual(values = colors) +
  scale_shape_manual(values = shapes) +
  scale_y_continuous(limits = c(20, 30)) +  # 设置纵坐标范围
  scale_x_continuous(breaks = seq(1, 9, by = 1), limits = c(1, 9)) +  # 设置横坐标范围和间隔
  theme_minimal(base_size = 6) +
  theme(
    plot.title = element_text(size = 6, face = "bold"),
    axis.title = element_text(size = 6),
    axis.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 6),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black")
  )
       
ggsave(lineplot, plot = line_plot, width = 3, height = 2)
line_plot


## 进行T-test
# 分组
control <- data_long %>% filter(Group == "NC")
MD <- data_long %>% filter(Group == "MD")
LMAT <- data_long %>% filter(Group == "LMAT")
HMAT <- data_long %>% filter(Group == "HMAT")


# 进行T检验
t_test_results <- list(
  Control_vs_MD = t.test(control$Value, MD$Value),
  Control_vs_LMAT = t.test(control$Value, LMAT$Value),
  Control_vs_HMAT = t.test(control$Value, HMAT$Value),
  MD_vs_LMAT = t.test(MD$Value, LMAT$Value),
  MD_vs_HMAT = t.test(MD$Value, HMAT$Value),
  LMAT_vs_HMAT = t.test(LMAT$Value, HMAT$Value)
)

# 使用 broom 包中的 tidy 函数将结果转换为数据框，并添加 comparison 列
t_test_results_df <- t_test_results %>%
  map_df(tidy, .id = "comparison")
# 保存T检验结果为txt文件            
write.table(t_test_results_df, file = ttest, sep = "\t", row.names = FALSE, quote = FALSE)
t_test_results_df


## 单因素方差分析(ANOVA)
anova_results <- aov(Value ~ Group, data = data_long)
# 展示ANOVA结果
summary(anova_results)
anova_summary <- summary(anova_results)
# 保存ANOVA结果为txt文件                 
capture.output(anova_summary, file = ANOVAt1)
# 可视化ANOVA结果并保存为PDF文件
anova_plot <- ggboxplot(data_long, x = "Group", y = "Value", 
                        color = "Group", palette = colors, 
                        add = "jitter") + 
  #geom_boxplot(outlier.size = 0, size = 0.75, aes(color = Group)) +  # 调整箱线图的描边宽度
  stat_compare_means(method = "anova", label = "p.signif") +
  theme_minimal(base_size = 6) +
  theme(
    plot.title = element_text(size = 6, face = "bold"),
    axis.title = element_text(size = 6),
    axis.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 6),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black")
  )
# 文件保存
ggsave(ANOVAt2, plot = anova_plot, width = 3, height = 3)
anova_plot


## 克鲁斯卡尔-沃利斯检验kruskal
kruskal_results <- kruskal.test(Value ~ Group, data = data_long)
# 展示克鲁斯卡尔-沃利斯检验结果
kruskal_results                           
capture.output(kruskal_results, file = kruskal)

```    





## 18天血糖变化图
```{r}
# 软件检测和安装
library(ggplot2)
library(dplyr)
library(tidyr)
library(broom)
library(purrr)
library(ggpubr) # 用于ANOVA结果可视化

# 文件夹位置
file1 = "C:/Matrine_bodydata/"
# 具体文件前标
part = "part_II_"
name = "Matrine_18days_bloodsugar"
# 文件后标
filemethod1 = "_line_plot"
filemethod2 = "_kruskal"
filemethod3 = "_t_test"
filemethod4 = "_ANOVA"
# 文件种类
filetype1 = ".txt"
filetype2 = ".pdf"
# 生成文件名
datafile <- paste(file1,part,name,filetype1,sep ="")
lineplot <- paste(file1,part,name,filemethod1,filetype2,sep ="")
ttest <- paste(file1,part,name,filemethod3,filetype1,sep ="")
ANOVAt1 <- paste(file1,part,name,filemethod4,filetype1,sep ="")
ANOVAt2 <- paste(file1,part,name,filemethod4,filetype2,sep ="")
kruskal <- paste(file1,part,name,filemethod2,filetype1,sep ="")

print(datafile)
print(lineplot)
print(ttest)
print(ANOVAt1)
print(ANOVAt2)
print(kruskal)

# 读取数据文件
data <- read.table(datafile, header = TRUE, sep = "\t")
# 检查数据框架结构
str(data)
# 转换数据框为长格式，并根据列名称分组
data_long <- data %>%
  pivot_longer(-Time_day, names_to = "Replicate", values_to = "Value") %>%
  mutate(Group = case_when(
    grepl("NC", Replicate) ~ "NC",
    grepl("MD", Replicate) ~ "MD",
    grepl("LMAT", Replicate) ~ "LMAT",
    grepl("HMAT", Replicate) ~ "HMAT"
  ))
# 计算平均值和标准误差
data_summary <- data_long %>%
  group_by(Time_day, Group) %>%
  summarise(
    Mean = mean(Value),
    SE = sd(Value) / sqrt(n())
  )

# 绘制折线图并保存为 PDF 文件
# 高级配色方案 
#colors <- c("NC" = "#440154FF", "MD" = "#31688EFF", "LMAT" = "#35B779FF", "HMAT" = "#FDE725FF")
#colors <- c("NC" = "#FBB4AE", "MD" = "#B3CDE3", "LMAT" = "#CCEBC5", "HMAT" = "#DECBE4")
#colors <- c("NC" = "#1b9e77", "MD" = "#d95f02", "LMAT" = "#7570b3", "HMAT" = "#e7298a" )
#colors <- c("NC" = "#7FC97F", "MD" = "#BEAED4", "LMAT" = "#FDC086", "HMAT" = "#FFFF99")
colors <- c("NC" = "#D7191C", "MD" = "#FDAE61", "LMAT" = "#ABDDA4", "HMAT" = "#2B83BA")
#colors <- c("NC" = "#A6CEE3", "MD" = "#1F78B4", "LMAT" = "#B2DF8A", "HMAT" = "#33A02C")
shapes <- c("NC" = 8, "MD" = 9, "LMAT" = 10, "HMAT" = 11)

# 绘制折线图并保存为 PDF 文件
line_plot <- ggplot(data_summary, aes(x = Time_day, y = Mean, color = Group, shape = Group)) +
  geom_line(size = 0.25) +
  geom_point(size = 0.75) +
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.25) +
  labs(x = "Time/day", y = "Mean Value ± SE", title = "OTGG Test Data with Error Bars") +
  scale_color_manual(values = colors) +
  scale_shape_manual(values = shapes) +
  scale_y_continuous(limits = c(0, 30)) +  # 设置纵坐标范围
  scale_x_continuous(breaks = seq(0, 18, by = 1), limits = c(0, 18)) +  # 设置横坐标范围和间隔
  theme_minimal(base_size = 6) +
  theme(
    plot.title = element_text(size = 6, face = "bold"),
    axis.title = element_text(size = 6),
    axis.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 6),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black")
  )
       
ggsave(lineplot, plot = line_plot, width = 3, height = 2)
line_plot


## 进行T-test
# 分组
control <- data_long %>% filter(Group == "NC")
MD <- data_long %>% filter(Group == "MD")
LMAT <- data_long %>% filter(Group == "LMAT")
HMAT <- data_long %>% filter(Group == "HMAT")


# 进行T检验
t_test_results <- list(
  Control_vs_MD = t.test(control$Value, MD$Value),
  Control_vs_LMAT = t.test(control$Value, LMAT$Value),
  Control_vs_HMAT = t.test(control$Value, HMAT$Value),
  MD_vs_LMAT = t.test(MD$Value, LMAT$Value),
  MD_vs_HMAT = t.test(MD$Value, HMAT$Value),
  LMAT_vs_HMAT = t.test(LMAT$Value, HMAT$Value)
)

# 使用 broom 包中的 tidy 函数将结果转换为数据框，并添加 comparison 列
t_test_results_df <- t_test_results %>%
  map_df(tidy, .id = "comparison")
# 保存T检验结果为txt文件            
write.table(t_test_results_df, file = ttest, sep = "\t", row.names = FALSE, quote = FALSE)
t_test_results_df


## 单因素方差分析(ANOVA)
anova_results <- aov(Value ~ Group, data = data_long)
# 展示ANOVA结果
summary(anova_results)
anova_summary <- summary(anova_results)
# 保存ANOVA结果为txt文件                 
capture.output(anova_summary, file = ANOVAt1)
# 可视化ANOVA结果并保存为PDF文件
anova_plot <- ggboxplot(data_long, x = "Group", y = "Value", 
                        color = "Group", palette = colors, 
                        add = "jitter") + 
  #geom_boxplot(outlier.size = 0, size = 0.75, aes(color = Group)) +  # 调整箱线图的描边宽度
  stat_compare_means(method = "anova", label = "p.signif") +
  theme_minimal(base_size = 6) +
  theme(
    plot.title = element_text(size = 6, face = "bold"),
    axis.title = element_text(size = 6),
    axis.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 6),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black")
  )
# 文件保存
ggsave(ANOVAt2, plot = anova_plot, width = 3, height = 3)
anova_plot


## 克鲁斯卡尔-沃利斯检验kruskal
kruskal_results <- kruskal.test(Value ~ Group, data = data_long)
# 展示克鲁斯卡尔-沃利斯检验结果
kruskal_results                           
capture.output(kruskal_results, file = kruskal)

```    




## 8周饮食量变化
```{r}
# 软件检测和安装
library(ggplot2)
library(dplyr)
library(tidyr)
library(broom)
library(purrr)
library(ggpubr) # 用于ANOVA结果可视化

# 文件夹位置
file1 = "C:/Matrine_bodydata/"
# 具体文件前标
part = "part_II_"
name = "Matrine_8weeks_dietweight"
# 文件后标
filemethod1 = "_line_plot"
filemethod2 = "_kruskal"
filemethod3 = "_t_test"
filemethod4 = "_ANOVA"
# 文件种类
filetype1 = ".txt"
filetype2 = ".pdf"
# 生成文件名
datafile <- paste(file1,part,name,filetype1,sep ="")
lineplot <- paste(file1,part,name,filemethod1,filetype2,sep ="")
ttest <- paste(file1,part,name,filemethod3,filetype1,sep ="")
ANOVAt1 <- paste(file1,part,name,filemethod4,filetype1,sep ="")
ANOVAt2 <- paste(file1,part,name,filemethod4,filetype2,sep ="")
kruskal <- paste(file1,part,name,filemethod2,filetype1,sep ="")

print(datafile)
print(lineplot)
print(ttest)
print(ANOVAt1)
print(ANOVAt2)
print(kruskal)

# 读取数据文件
data <- read.table(datafile, header = TRUE, sep = "\t")
# 检查数据框架结构
str(data)
# 转换数据框为长格式，并根据列名称分组
data_long <- data %>%
  pivot_longer(-Weeks, names_to = "Replicate", values_to = "Value") %>%
  mutate(Group = case_when(
    grepl("NC", Replicate) ~ "NC",
    grepl("MD", Replicate) ~ "MD",
    grepl("LMAT", Replicate) ~ "LMAT",
    grepl("HMAT", Replicate) ~ "HMAT"
  ))
# 计算平均值和标准误差
data_summary <- data_long %>%
  group_by(Weeks, Group) %>%
  summarise(
    Mean = mean(Value),
    SE = sd(Value) / sqrt(n())
  )

# 绘制折线图并保存为 PDF 文件
# 高级配色方案 
#colors <- c("NC" = "#440154FF", "MD" = "#31688EFF", "LMAT" = "#35B779FF", "HMAT" = "#FDE725FF")
#colors <- c("NC" = "#FBB4AE", "MD" = "#B3CDE3", "LMAT" = "#CCEBC5", "HMAT" = "#DECBE4")
#colors <- c("NC" = "#1b9e77", "MD" = "#d95f02", "LMAT" = "#7570b3", "HMAT" = "#e7298a" )
#colors <- c("NC" = "#7FC97F", "MD" = "#BEAED4", "LMAT" = "#FDC086", "HMAT" = "#FFFF99")
colors <- c("NC" = "#D7191C", "MD" = "#FDAE61", "LMAT" = "#ABDDA4", "HMAT" = "#2B83BA")
#colors <- c("NC" = "#A6CEE3", "MD" = "#1F78B4", "LMAT" = "#B2DF8A", "HMAT" = "#33A02C")
shapes <- c("NC" = 8, "MD" = 9, "LMAT" = 10, "HMAT" = 11)

# 绘制折线图并保存为 PDF 文件
line_plot <- ggplot(data_summary, aes(x = Weeks, y = Mean, color = Group, shape = Group)) +
  geom_line(size = 0.25) +
  geom_point(size = 0.75) +
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE), width = 0.25, size = 0.25) +
  labs(x = "Weeks", y = "Mean Value ± SE", title = "OTGG Test Data with Error Bars") +
  scale_color_manual(values = colors) +
  scale_shape_manual(values = shapes) +
  scale_y_continuous(limits = c(5, 35)) +  # 设置纵坐标范围
  scale_x_continuous(breaks = seq(2, 9, by = 1), limits = c(2, 9)) +  # 设置横坐标范围和间隔
  theme_minimal(base_size = 6) +
  theme(
    plot.title = element_text(size = 6, face = "bold"),
    axis.title = element_text(size = 6),
    axis.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 6),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black")
  )
       
ggsave(lineplot, plot = line_plot, width = 3, height = 2)
line_plot


## 进行T-test
# 分组
control <- data_long %>% filter(Group == "NC")
MD <- data_long %>% filter(Group == "MD")
LMAT <- data_long %>% filter(Group == "LMAT")
HMAT <- data_long %>% filter(Group == "HMAT")


# 进行T检验
t_test_results <- list(
  Control_vs_MD = t.test(control$Value, MD$Value),
  Control_vs_LMAT = t.test(control$Value, LMAT$Value),
  Control_vs_HMAT = t.test(control$Value, HMAT$Value),
  MD_vs_LMAT = t.test(MD$Value, LMAT$Value),
  MD_vs_HMAT = t.test(MD$Value, HMAT$Value),
  LMAT_vs_HMAT = t.test(LMAT$Value, HMAT$Value)
)

# 使用 broom 包中的 tidy 函数将结果转换为数据框，并添加 comparison 列
t_test_results_df <- t_test_results %>%
  map_df(tidy, .id = "comparison")
# 保存T检验结果为txt文件            
write.table(t_test_results_df, file = ttest, sep = "\t", row.names = FALSE, quote = FALSE)
t_test_results_df


## 单因素方差分析(ANOVA)
anova_results <- aov(Value ~ Group, data = data_long)
# 展示ANOVA结果
summary(anova_results)
anova_summary <- summary(anova_results)
# 保存ANOVA结果为txt文件                 
capture.output(anova_summary, file = ANOVAt1)
# 可视化ANOVA结果并保存为PDF文件
anova_plot <- ggboxplot(data_long, x = "Group", y = "Value", 
                        color = "Group", palette = colors, 
                        add = "jitter") + 
  #geom_boxplot(outlier.size = 0, size = 0.75, aes(color = Group)) +  # 调整箱线图的描边宽度
  stat_compare_means(method = "anova", label = "p.signif") +
  theme_minimal(base_size = 6) +
  theme(
    plot.title = element_text(size = 6, face = "bold"),
    axis.title = element_text(size = 6),
    axis.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 6),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(color = "black")
  )
# 文件保存
ggsave(ANOVAt2, plot = anova_plot, width = 3, height = 3)
anova_plot


## 克鲁斯卡尔-沃利斯检验kruskal
kruskal_results <- kruskal.test(Value ~ Group, data = data_long)
# 展示克鲁斯卡尔-沃利斯检验结果
kruskal_results                           
capture.output(kruskal_results, file = kruskal)

```    










 
